apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-itn-deployment
  labels:
    app: pl-itn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pl-itn
  template:
    metadata:
      labels:
        app: pl-itn
    spec:
      volumes:
        - name: fst-storage
          hostPath:
            path: /mnt/fst_models
            type: Directory
      containers:
      - name: pl-itn
        image: pl_itn:test
        ports:
        - containerPort: 10010
        volumeMounts:
          - name: fst-storage
            mountPath: /fst_models