apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pl-itn-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /metrics
  selector:
    matchLabels:
      app: pl-itn-service