apiVersion: v1
kind: Service
metadata:
  name: pl-itn-service
  labels:
    job: pl-itn-service
    app: pl-itn-service
spec:
  type: NodePort
  selector:
    app: pl-itn
  ports:
    - name: web
      protocol: TCP
      port: 10010
      targetPort: 8000
      nodePort: 30010