apiVersion: v1
kind: Service
metadata:
  name: pl-itn-service
spec:
  type: NodePort
  selector:
    app: pl-itn
  ports:
    - protocol: TCP
      port: 10010
      targetPort: 10010
      nodePort: 30010