# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Install pl_itn and perform tests.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        case:
        - "cardinals_basic_forms"
        - "cardinals_declined"
        - "ordinals"
        - "empty_grammar"
        - "full_normalization"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[test]'
    - name: Test
      run: |
        python3 build_grammar/build_grammar.py -c "tests/configs/${{ matrix.case }}.yaml" -g "${{ matrix.case }}"
        pytest tests --config "tests/configs/${{ matrix.case }}.yaml" --grammars "${{ matrix.case }}"