name: Upload images to dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build grpc service image
        uses: docker/build-push-action@v4
        with:
          context: grpc_service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pl-itn-grpc-service:latest
      -
        name: Build restful service image
        uses: docker/build-push-action@v4
        with:
          context: restful_service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pl-itn-rest-service:latest